### ISSUE TITLE
1 Moviedetailpage | Basic Styling 

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#1]
## Value Proposition

**As a** user

**I need** have to see the basic information to the recommended movie  

**to be able to** have an idea if I want to watch it 

## Description
![Bildschirmfoto 2022-12-12 um 10 40 41](https://user-images.githubusercontent.com/96984853/207012634-8953d369-e634-42ca-be95-efbbc31e7249.png)

## Acceptance Criteria

The following content is shown: 
- [ ] a movie poster (not clickable) 
- [ ] a headline (max 2 rows)
- [ ] tags with information about the duration and genre 
- [ ] a movie description which is folded in (as default - max 200 characters) and can be unfolded by click (all characters)
- [ ] on the main page is a text link, routing to the movie site 

## Tasks
- [x] the basic next/react setup is done  
- [x] the page is deposited at Github  
- [x] styled components are integrated and used
- [x] there is a Vercel domain linked to the github project
- [x] Poppins Font is downloaded and fully integrated https://fonts.google.com/specimen/Poppins
- [ ] the movie poster is linking to an external URL 
- [ ] tags are different Key/value pairs, but have the same styling (duration = duration, genre = genre array)
- [ ] the "read more" button is a useState with the status true/false 
- [ ] Step 1: I use Mocked data to search through a test movie array with 5 movies (random pick)
