### ISSUE TITLE
6 Wizard | Question 3 - mood

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#10]
## Value Proposition

**As a** use

**I need** choose a fitting mood for my movie

**to be able to** find a suitable movie.

## Description
<img width="327" alt="Bildschirmfoto 2022-12-16 um 15 29 20" src="https://user-images.githubusercontent.com/96984853/208120238-7232f817-6fe5-415f-bbe5-ee6ea22522d6.png">

## Acceptance Criteria

- [ ] by choosing an answer on the second wizard step, the user is redirected to this question
- [ ] the headline is shown: "Wie geht es dir heute?"
- [ ] the user can choose between 4 options: 
- [ ] After clicking the next button the user will be redirected to the movie recommendation page, where a movie is shown with the chosen length (step 1), the chosen production time period (step2) and the fitting mood (step 3)

## Tasks
- [ ] the filteredMovies array is used to filter through
- [ ] the movies are filtered based on a new custom field, which I have to add to my data.js
- [ ] the "mood filter" will also be displayed on the movie details page as a tag 
- [ ] The user is redirected to a dynamic URL, which is rendered by the movie ID

**Comment by NeeleWaehnke** [comment]
Sieht gut aus :) bin sehr gespannt auf deine App, richtig cooles Konzept auf jeden Fall!

**Comment by flipkoehler** [comment]
danke dir :) 
es folgen noch ein paar coole Funktionen (hoffentlich)
