### ISSUE TITLE
7 Wizard | Question 4 - other requirement

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#11]
## Value Proposition

**As a** user

**I need** choose a fitting mood for my movie

**to be able to** find a suitable movie.

## Description

<img width="320" alt="Bildschirmfoto 2022-12-17 um 11 44 41" src="https://user-images.githubusercontent.com/96984853/208237972-4ee93a1a-c2b5-407e-b142-33c8703ce744.png">

## Acceptance Criteria

- [ ] by choosing an answer on the third wizard step, the user is redirected to this question
- [ ] the headline is shown: "Was für einen Anspruch darf dein Film haben?"
- [ ] the user can choose between 4 options (details are not decided yet)
- [ ] After clicking the next button the user will be redirected to the movie recommendation page, where a movie is shown with the chosen length (step 1), the chosen production time period (step2), the fitting mood (step 3) and the correct requirements from the last question

## Tasks
- [ ] the filteredMovies array is used to filter through
- [ ] the movies are filtered based on a new custom field, which I have to add to my data.js
- [ ] Since the chances of not finding a fitting movie increases, I will redirect the user to a movie recommondation with a disclaimer that the site hasn't find a correct movie. Also a link to the quiz is added to start over.
- [ ] the "requirement filter" will also be displayed on the movie details page as a tag 
- [ ] The user is redirected to a dynamic URL, which is rendered by the movie ID

**Comment by ufelgen** [comment]
ok jetzt sehe ich, wofür die leeren Daten da sind :) habe nichts auszusetzen! 

nur einen kleinen Vorschlag: "welchen Anspruch" statt "was für einen" 
und den Task hier "the "requirement filter" will also be displayed on the movie details page as a tag" versteh ich nicht... aber du bestimmt schon ;)
