### ISSUE TITLE
8 | Backend - add a database 

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#12]
## Value Proposition

**As a** developer 

**I need** save the data in a database

**to be able to** store it and edit it more comfortable 

## Description

I fully integrate a MongoDB to replace my movie Array saved in the data lib. 

## Acceptance Criteria

This is a backend task - so there are only Tasks for me. 

## Tasks

- [ ] setup a new mongoDB in Atlas 
- [ ] add a db folder to my project including the data model and a dbConnect.js
- [ ] write a local .env.local file - that will be added to the .gitignore
- [ ] setup the Atlas connection to the cloud  
- [ ] replace all the refers in the code from the old "data.js" file to the new database

**Comment by altanguellue** [comment]
good one! Have fun and luck connecting your database to your project!

**Comment by flipkoehler** [comment]
thank you Altan - i am a bit scared of this task 😨
