### ISSUE TITLE
9 Form | Add a new movie - step 1 

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#15]
## Value Proposition

**As a** user 

**I need** to contribute new movies 

**to be able to** let the movie database grow

## Description

<img width="235" alt="Bildschirmfoto 2022-12-19 um 11 12 36" src="https://user-images.githubusercontent.com/96984853/208401845-e4a02218-7eb9-410e-b941-e88a19ec6e48.png">

## Acceptance Criteria

- [ ] the user can navigate to this page by type in the browser (...domain/add-a-new-movie) or by clicking on the plus Icon (maybe not possible if the navigation follows this user story) 
- [ ] the user can paste in an URL from TMDB 
- [ ] If the user clicks on the button "Film jetzt einreichen", he/she will be redirected to a confirmation page including a text and a URL containing the movie id. By clicking on the Link, the user will see the moviedetailpage to the added movie

## Tasks

- [ ] the input filed needs to check if the domain starts with: https://www.themoviedb.org/movie/
- [ ] there will be an information if the link is correct 
- [ ] the placeholder in the Input field says "z.B. https://www.themoviedb.org/movie/MEIN-FILM"
By clicking on the button the following steps will happen: 
- [ ] 1. a new fetch containing the movie id will start and get the movie data
- [ ] 2. the movie data will be stored in the database
- [ ] 3. the routing will redirect the user to a page containing a text and the link to the new movie
