### ISSUE TITLE
2 Main Page | Logo and Introduction

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#2]
## Value Proposition

**As a** user

**I need** to understand the purpose of the website 

**to be able to** identify my new favourite movie page

## Description
![Bildschirmfoto 2022-12-09 um 16 06 20](https://user-images.githubusercontent.com/96984853/206731933-de12776c-4f10-4897-8f5a-8f5f36731a1b.png)

## Acceptance Criteria

- [ ] the logo is shown 
- [ ] On the main page is a short headline saying "Deine Filmempfehlung in vier einfachen Schritten"
- [ ] there is a description of the web page
- [ ] there are 3 icons explaining the benefits of movie flip

## Tasks

- [ ] styled components are integrated and used for the global styles (including the root colors, a flexbox container for the header and a max width)
- [ ] the header component is tested via unit tests
- [ ] the logo is a component of the header  
- [ ] headline is passed via a Prop to the  headline component (stored in App > Main > Headline Component)
- [ ] icons are attached as a svg. Intregation guide: https://blog.logrocket.com/how-to-use-svgs-in-react/
