### ISSUE TITLE
10 Form | Add a new movie - mood & occasion

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#21]
## Value Proposition

**As a** an content producer

**I need** to add tags to a movie

**to be able to** give the user a better recommendation based on their needs

## Description
![Bildschirmfoto 2023-01-05 um 10 34 18](https://user-images.githubusercontent.com/96984853/210747950-1f395b31-f213-47a6-966b-9bb98e0b6f84.png)

## Acceptance Criteria

- [ ] after selecting a movie, I can add tags for the mood
- [ ] and I can add tags for the occasion
- [ ] after clicking on "Film hinzufügen" the movie will be shown with the selected moods as Tags 

## Tasks

- [ ] the component used in Step 3 will be reused here 
- [ ] I have to check at least 2 moods and 2 occasion

**Comment by AntjeWalter** [comment]
Looks good to me! :)
