### ISSUE TITLE
11 Form | Add a new movie - further information (trailer, comment, facts)

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#23]
## Value Proposition

As a an content producer

I need to add further information to a movie

to be able to give the user a better recommendation based on their needs

## Description

![Bildschirmfoto 2023-01-05 um 16 13 42](https://user-images.githubusercontent.com/96984853/210813581-5633660b-40b9-47ce-bf0b-2d51c33b041c.png)

## Acceptance Criteria

- [ ] after selecting a movie, I can add a text to describe the recommendation (mandatory)
- [ ]  and I can add fun facts about the movie (optional)
- [ ]  and I dan add a link to a trailer (optional) 
- [ ]  after clicking on "Film hinzufügen" the movie will be shown with the selected moods as Tags
- [ ]  there will be a short text explaining what to do

## Tasks

 - [ ] I have to disable the button before the user filled out the mandatory fields 
 - [ ] everything that has been filled out is stored in my database
 - [ ] if possible the user will be guided through 2 steps

**Comment by AntjeWalter** [comment]
This app is just sick. I am pretty impressed! 🤩
