### ISSUE TITLE
12 Quiz | Redesign and custom mood picker

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#26]
## Value Proposition

**As a** user 

**I need** uncheck preselected moods 

**to be able to** get the best movie recommendation 

Scribble / design or text

![Bildschirmfoto 2023-01-08 um 13 31 49](https://user-images.githubusercontent.com/96984853/211196174-e5403fcf-ee7a-49a1-a8ab-64415ece55f3.png)

## Acceptance Criteria

- [ ] On the right side of the quiz (on mobile above) you can see new graphics that makes the design a bit more appealing
- [ ] In the third step, in addition to selecting a "genre", you can also select and deselect the subcategories
- [ ] The arrow is changing on click
- [ ] Only movies that have moods of the corresponding selection are displayed 

## Tasks

(for developers team)

- [ ] The array selectedMoods is updated according to the selection
- [ ] A back button is added (only clickable in step 2,3,4)
- [ ] The new SVG graphics are inserted via flexbox and have mediaqueries
- [ ] The detail selection of the moods can be expanded and collapsed
