### ISSUE TITLE
14 | Movie Detail Page | Add new fields & Redesign 

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#28]
## Value Proposition

**As a** user

**I need** to have all information about a movie

**to be able to** decide if it fits to my needs

## Description

Unfortunately there is no design yet. But all fields are displayed that are currently stored in the data (not yet implemented)

## Acceptance Criteria

The following fields are displayed on the detail page:
- [ ] Trailer (Link to YouTube)
- [ ] recommendation text
- [ ] occasions
- [ ] The design is also displayed user-friendly on desktop

## Tasks

- [ ] Use flexbox for showing the movie poster more responsive 
- [ ] the data is already passed to the detailpage - no further logic 
- [ ] the link to the trailer is a "target blank" link
