### ISSUE TITLE
4 Wizard | Question 2 - release date

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#4]
## Value Proposition

**As a** user

**I need** choose between different years the movie was produced 

**to be able to** find a suitable movie.

## Description

![Bildschirmfoto 2022-12-09 um 15 31 07](https://user-images.githubusercontent.com/96984853/206724819-ae602662-3a84-49b2-ac12-22ac316e3db9.png)

## Acceptance Criteria

- [ ] by choosing an answer on the first wizard step, the user is redirected to this question
- [ ] the headline is shown: "Wie alt darf dein Film sein?"
- [ ] the user can choose between 4 options: "aktuelle Filme, moderne Klassiker, Oldies, ist mir egal" 
- [ ] After clicking a button the user will be redirected to the movie recommendation page, where a movie is shown with the chosen length (step 1) and the chosen production time period (this step)

## Tasks
- [ ]  every question is located in a wizard parent component (app > main > wizard > questionProductionYear)
- [ ] the test movie array is used to filter through
- [ ] The movies are filtered based on the release date:  aktuelle Filme (>2010), moderne Klassiker(1987-2010), Oldies (<1987), ist mir egal (every movie)
- [ ] after hitting one of the four options, the user is redirected to a dynamic URL, which is rendered by the movie slug or ID
