### ISSUE TITLE
Einen Film mit...

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#40]
## Value Proposition

Übersicht von bekannten Schauspieler:innen

## Description

Scribble / design or text

## Acceptance Criteria

- [ ] die Seite ist unter: "einen-film-mit" erreichbar
- [ ] Die Bühne auf der Startseite verlinkt auf diese Seite
- [ ] Inhalte: Bild, Namen, kurze Beschreibung (2-3 Sätze)
- [ ] Bei add-a-movie gibt es ein zusätzliches optionales Feld (nicht im Quiz). Der Wert kann mit Check auf true gesetzt werden.  

## Tasks

- [ ] Bilder via Google Free Common: https://www.google.com/search?q=tom%20hanks&tbm=isch&hl=de&tbs=il:cl&rlz=1C1GCEA_enDE1040DE1040&sa=X&ved=0CAAQ1vwEahcKEwiQ3I2x5NP9AhUAAAAAHQAAAAAQAw&biw=1903&bih=929#imgrc=fb2kko6oTHQa8M
