### ISSUE TITLE
SEO dies das

### ISSUE THREAD

**Issue by flipkoehler** [flipkoehler/capstone-project-ts#57]
## Value Proposition

Als Google will ich die Seite besser listen können

## Acceptance Criteria

- [ ] Title überall einfügen
- [ ] Headlines checken 
- [ ] CLS angucken 
- [ ] Descriptions 
- [ ] Alt Tags checken 
- [ ] xml sitemap 
- [ ] robots.txt (nofollow addamovie)
- [ ] slug url auf deutsche Filme umstellen 
- [ ] 404 mit Statuscode 404 

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
